apps/example/src/components/Chat.tsx, packages/react-rtc/package.json, packages/react-rtc/src/index.tsx
[Nanoid](https://www.npmjs.com/package/nanoid) appears to be much better alternative to uuid. You can check this article: https://www.npmjs.com/package/nanoid
**[REPLACED WITH CRYPTO](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)**
=> feat: replaced uuid with crypto

apps/example/src/components/Chat.tsx, packages/react-rtc/src/index.tsx
=> fixed events display name and some minor fix

packages/react-rtc/src/index.tsx
Added error handler. Still needs to properly handle errors.
=> refactor: add error handler

packages/react-rtc/package.json, packages/react-rtc/rollup.config.ts, yarn.lock
GH card ticket "link": https://github.com/torolocos/react-rtc/issues/19
Closes #19
=> chore: setup rollup build

.github/workflows/ci-checks.yml, .husky/pre-commit, .lintstagedrc.json, package.json, packages/react-rtc/package.json, turbo.json, yarn.lock
Added husky and pre-commit hook.
=> chore: setup husky

apps/example/src/components/Chat.tsx, apps/example/src/index.tsx, packages/react-rtc/src/index.tsx
Removed keyword chat from package.
=> refactor: replaced chat with rtc

package.json, yarn.lock
=> chore(dev-dependencies): update turbo

apps/example/src/components/Chat.tsx, packages/react-rtc/src/RtcProvider.tsx, packages/react-rtc/src/index.ts, packages/react-rtc/src/types.ts
=> fix(Message): made Event prop mandatory

.lintstagedrc.json, packages/react-rtc/.eslintrc.json, packages/react-rtc/src/RtcContext.ts, packages/react-rtc/src/RtcProvider.tsx
=> chore: fix lint-staged on commit

packages/react-rtc/package.json, packages/react-rtc/rollup.config.ts, packages/react-rtc/tsconfig.json, yarn.lock
Improve build performance with esbuild. Removed cjs build.
=> chore: esbuild

.github/workflows/ci-checks.yml, .github/workflows/npm-publish.yml, packages/react-rtc/src/RtcProvider.tsx
=> chore: Slack integration

apps/example/src/components/Chat.tsx, packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/usePubSub.ts, packages/react-rtc/src/types.ts
=> feat: add listener options

packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/models/Peer.ts, packages/react-rtc/src/types.ts
=> feat: peer model

apps/example/src/App.tsx, apps/example/src/components/Chat.tsx, apps/example/src/index.tsx
Docs: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
=> feat: react root api update

apps/example/src/components/Chat.tsx, packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/useSignaling.ts, packages/react-rtc/src/index.ts, packages/react-rtc/src/models/Message.ts, packages/react-rtc/src/models/Peer.ts, packages/react-rtc/src/types.ts, packages/react-rtc/tsconfig.json
Removed `displayName` property. This is first part, second will be rework of metadata.
=> refactor: remove display name

packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/useSignaling.ts
Remove `peerConnections` map dependenci from `useSignaling` hook. Connect, discconect function defined in `usePeerConnection`.
=> refactor: connect-disconnect

packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/usePubSub.ts, packages/react-rtc/src/types.ts
Replaced leave callback with event dispatcher.
=> feat: Leave event

packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/usePeerConnection.ts
Pulled local uuid to provider.
=> refactor: Pull local UUID to provider

packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/useErrorHandler.ts, packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/usePubSub.ts, packages/react-rtc/src/types.ts
=> feat: Error handler hook

apps/web-example/.eslintrc.json, apps/web-example/package.json, apps/web-example/src/components/PageLayout/index.tsx, apps/web-example/src/features/auth/contexts/user.tsx, apps/web-example/src/features/auth/types.ts, apps/web-example/src/features/chat/components/Chat/index.tsx, apps/web-example/src/features/chat/components/Chat/styled.ts, apps/web-example/src/features/chat/components/ChatHeader/index.tsx, apps/web-example/src/features/chat/components/ChatHeader/styled.ts, apps/web-example/src/features/chat/components/ChatInput/index.tsx, apps/web-example/src/features/chat/components/ChatInput/styled.ts, apps/web-example/src/features/chat/components/index.ts, apps/web-example/src/features/chat/hooks/message/index.ts, apps/web-example/src/features/chat/pages/ChatPage/index.tsx, apps/web-example/src/features/chat/pages/ChatPage/styled.ts, apps/web-example/src/features/ui/TextInput/index.tsx, apps/web-example/src/features/ui/TextInput/styled.ts, apps/web-example/src/features/ui/index.ts, apps/web-example/src/features/ui/theme/globalStyles.ts, apps/web-example/src/features/ui/theme/stitches.config.ts, apps/web-example/src/pages/_app.tsx, apps/web-example/src/pages/index.tsx, apps/web-example/tsconfig.json, yarn.lock
=> feat(WebExample): created Chat Page WIP

.github/workflows/main.yml
Resolves #18 added action for preview and production deployment.
=> ci: preview and production deployment

packages/react-rtc/package.json
Added keywords for react-rtc package.
=> chore: react-rtc keywords

package.json, packages/react-rtc/package.json
Reset react-rtc package version.
=> chore: reset version

packages/react-rtc/README.md
=> docs(react-rtc): add readme

apps/example/src/components/Chat.tsx, packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/useSignaling.ts, packages/react-rtc/src/types.ts
=> feat: add enter event

LICENSE
=> chore: add licence

apps/example/src/App.tsx, packages/react-rtc/README.md
Added code example to react-rtc README and resolves #74.
=> docs: add code example to react-rtc readme

README.md
Added links to apps and packages in README and resolves #79.
=> docs(README): update project information

turbo.json
=> chore: remove unused turbo config

.github/workflows/main.yml, README.md, codecov.yml, packages/react-rtc/jest.config.json, turbo.json
Added [Codecov](https://app.codecov.io/) for code coverage measurement, resolves #89.
=> ci: measure code coverage

packages/react-rtc/src/hooks/__tests__/usePeers.test.ts, packages/react-rtc/src/hooks/__tests__/useSignaling.test.ts
Added test for `useSignaling` hook.
=> test: add use signaling test

apps/example/package.json, apps/example/src/components/Chat.tsx, apps/example/src/components/styles.css, packages/react-rtc/src/contexts/RtcProvider.tsx, packages/react-rtc/src/hooks/__tests__/usePeers.test.ts, packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/usePeers.ts, packages/react-rtc/src/types.ts
Implemented "handshake" to example app.
=> feat: handshake

.github/workflows/main.yml, apps/signaling/package.json, apps/signaling/src/index.ts, codecov.yml, packages/signaling-server/README.md, packages/signaling-server/jest.config.json, packages/signaling-server/package.json, packages/signaling-server/src/__tests__/send.test.ts, packages/signaling-server/src/__tests__/utils.test.ts, packages/signaling-server/src/index.ts, packages/signaling-server/src/send.ts, packages/signaling-server/src/utils.ts, packages/signaling-server/tsconfig.json, yarn.lock
Resolves #95 and resolves #91.
=> feat: signaling server package

.release-it.json
Added changelog sections to release-it config.
=> chore: add changelog sections

packages/react-rtc/src/hooks/usePeerConnection.ts, packages/react-rtc/src/hooks/useSignaling.ts, packages/react-rtc/src/types.ts
Removed new peer prop, it is not needed anymore.
=> refactor: remove new peer flag

.vscode/launch.json, apps/example/package.json, packages/react-rtc/package.json, packages/react-rtc/tsconfig.json
=> chore: add debug config

package.json, turbo.json
=> chore: update turbo config

apps/web-example/package.json, yarn.lock
Fixed issue with `yarn add <package>`. Link to issue: https://github.com/yarnpkg/yarn/issues/7807
```shell
error An unexpected error occurred: "expected workspace package to exist for \"jest-util\"".
```
=> chore: fix yarn add

packages/react-rtc/package.json, packages/react-rtc/src/hooks/__tests__/usePubSub.test.ts, packages/react-rtc/src/hooks/usePeerConnection.ts
Replaced `crypto.randomUUID` with nanoid package.
=> refactor: replace random uuid with nanoid

.release-it.json
Added signing for release commits. See: https://github.com/release-it/release-it/issues/350
=> chore: sign release commit

.github/workflows/main.yml
=> ci: rename deploy step

.github/workflows/main.yml
Bump codecov GH action, see: https://github.com/codecov/codecov-action#migration-from-v1-to-v3
=> ci: bump codecov action
